config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"
  get "pages/secret"
  get "/login", to: "user_sessions#new"
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  helper_method :current_user

  def current_user
    @current_user ||= session[:user_id] && User.find_by(id: session[:user_id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index 
  end

  def secret

    if current_user.blank?
      render plain: "401 Unauthorised", status: :unauthorized
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(name: params[:user][:name])          # Grab user by their ID.

    # Authenticate is a method from has_secure_password on the user model.
    if @user && @user.authenticate(params[:user][:password])  # If user can be found and password matches...
      session[:user_id] = @user.id                            # Create session with the user's ID.
      redirect_to root_path
    else 
      flash[:alert] = "Login failed."
      redirect_to new_user_session_path
    end
  end

  def destroy
    session[:user_id] = nil 
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save 
      flash[:notice] = "User created."
      redirect_to users_path 
    else 
      flash[:alert] = "User not created."
      render :new, status: :unprocessable_entity
    end
  end

  private 

    def user_params 
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Password Test" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |type, message| %>
      <div>
        <% message %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<% if current_user %>
    <h1>Welcome, <%= current_user.name %></h1>
    <h2>My Account</h2>
    <%= link_to "View Account", "/pages/secret" %> | 
    <%= link_to "Logout", user_session_path(current_user), data: { turbo_method: :delete } %>
<% else %>
    <h1>Index Page</h1>
    <%= link_to "Login", login_path %></br />
    <p>If you were logged in, you could access the <%= link_to "Secret Page", "/pages/secret" %>
<% end %>

app/views/pages/secret.html.erb
<h1>Secret page</h1>

<%= link_to "My Account", root_path %>

<p>Only logged in users can see this.</p>

<p>You are only able to see this because you are logged in. This could be, for example,
    a list of your posts, or other things created via a model. That is because you are logged in via: 
    the current_user method on the Application Controller:</p>

<code>  
  helper_method :current_user<br /><br />
  def current_user<br /><br />
    @current_user ||= session[:user_id] && User.find_by(id: session[:user_id])<br /><br />
  end<br /><br /> 
</code>

<p>This code makes current_user a method available to any controller and view. It only works because you first have
to login via user_sessions/new and provide a password which, once hashed, matches the password_digest stored in the 
database. This sets session[:user_id]. Then, in this method, it sets the instance variable @current_user equal to
    the user via User.find_by(), placing the id of the user via the session.</p>

<p>So, in short, it goes: make user ->
    login user (matched password) ->
    create session ->
    use session to provide id -> 
    use that id to run User.find_by() and then return that object as the implicit return value of current_user. Now, 
    on the pages you want it to, a logged-in user can do whatever.</p>

    ID: <%= current_user.id %><br />
    Name: <%= current_user.name %><br />
    Password_hash: <%= current_user.password_digest %><br />

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/new.html.erb
<h1 class="centre">Login</h1>

<div id="login">
    <%= form_with model: @user, url: user_sessions_path do |f| %>
        <div>
            <%= f.label :name %>
            <%= f.text_field :name %>
        </div>
        <div>
            <%= f.label :password %>
            <%= f.password_field :password %>
        </div>
        <p>
            <%= f.submit %>
        </p>
    <% end %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>All Users</h1>

<%= link_to "Sign Up", new_user_path %>

<table class="users">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
            <tr>
                <td><%= user.id %></td>
                <td><%= user.name %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/users/new.html.erb
<h1 class="centre">Create your account</h1>

<div class="messages">
    <%= form_with model: @user do |f| %>
        <% if @user.errors.any? %>
            <div>
                <ul>
                    <% @user.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
            </div>
    <% end %>
</div>

<div id="signup">
    <div>
        <%= f.label :name %>
        <%= f.text_field :name %><br />
    </div>
    <div>
        <%= f.label :password %>
        <%= f.password_field :password %><br />
    </div>
    <div>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %><br />
    </div>
    <p class="centre">
        <%= f.submit %>
    </p>
<% end %>

</div>